### ISSUE TITLE
Updating lag on training page

### ISSUE THREAD

**Issue by NunosDC** [OpenThrone/OpenThrone#10]
When training units I noticed that there is a lag between training the units and the You Have column. See attached capture.
![image](https://github.com/uaktags/DarkCurse-nextjs/assets/146961378/c9179816-767c-4aad-852f-e6210318fad3)

**Comment by Dragonsoulj** [comment]
This is still an issue. The success message shows, the citizens total in the stats scroll update, but the quantity for the citizen type doesn't update and the quantity to train field should honestly zero out so double-training doesn't occur.

**Comment by uaktags** [comment]
Reconfim please, i think this was just a regression in the new training component. Should be fix now though

**Comment by Dragonsoulj** [comment]
Seems fixed and also zeroes out. I'd mark this as closed.
