### ISSUE TITLE
Unit Conversion Ideas and Issue

### ISSUE THREAD

**Issue by NunosDC** [OpenThrone/OpenThrone#100]
So for the issue it is doing that little leave your info on the screen lag type thingy :P 
![image](https://github.com/OpenThrone/OpenThrone/assets/146961378/14679223-c882-410f-8caa-e6290871f35d)
As for the idea I think some logic for the input boxes might clear future peoples confusion for example there shouldn't be a way to train Soldiers in Box 1 to Soldiers in Box 2.

**Comment by uaktags** [comment]
Hmm, this lag is a weird one, but we're saying that purchases are working
