### ISSUE TITLE
Add "Total Refund" to bottom bar.

### ISSUE THREAD

**Issue by Dimez123** [OpenThrone/OpenThrone#101]
Is this intended?

i.e. I buy 1 offense item upgrade for 12375 (1pt charisma). It deducts the stated amount correctly.
I sell that 1 offense item upgrade, but it only returns 9281 gold, a flat 25% reduction. I heard of an intent to ensure sell cost is lower than purchase cost.

Is this that update coming into play? If so, I'd ask that the tooltip represent the actual amount the user can expect to receive.

**Comment by uaktags** [comment]
![image](https://github.com/OpenThrone/OpenThrone/assets/893684/996be06f-ba3e-46bc-85bd-cbe0174429e8)

It's listed in both Training and Armory.

**Comment by uaktags** [comment]
Maybe add "Total Refund" to the bottom bar in addition to Total Cost as well?

**Comment by NunosDC** [comment]
Total Refund Ammount would help address the toolbar needing to be wider on some devices

**Comment by uaktags** [comment]
Yea, we're still working on the banner's size breakpoints for responsiveness, but i'll get an update drafted up for adding Total Refund to the mix.

**Comment by Dimez123** [comment]
didnt even see that after ui change. Blind as bat, this post was useless. thank you

**Comment by uaktags** [comment]
Reopening until banner is resolved, updating the title now.

**Comment by uaktags** [comment]
Will be pushed to Prod later.
