### ISSUE TITLE
Issues with Deposits

### ISSUE THREAD

**Issue by JOHNNYGAZER** [OpenThrone/OpenThrone#104]
I was able to deposit gold with 0 deposits and the available deposit counter went to -1:

![image](https://github.com/OpenThrone/OpenThrone/assets/170389243/10784ae8-951a-418b-aa8d-58f694750854)

Also, if you click the deposit button with no value in the field it still takes away a deposit.

**Comment by uaktags** [comment]
I've implemented the fixes, the UX can still be worked on but atleast shows the error message now, and your deposit of 0 has been deleted. If you can confirm on your end, i'll go ahead and submit the commit and close out

**Comment by JOHNNYGAZER** [comment]
Looks good, the "0" deposit is gone, I can no longer deposit 0 and I can no longer go into the negative for deposits!
