### ISSUE TITLE
Cannot attack some users

### ISSUE THREAD

**Issue by Revenate39** [OpenThrone/OpenThrone#110]
Hopefully the title explains this one fairly well, but when attacking some users after selecting how many turns and pressing 'submit' no further action happens. I've noticed the issue only happens with those a who are the same or lower level than me. No issue attacking higher levels.

**Comment by uaktags** [comment]
Do you have any examples of users/user ids? I was able to attack you (level 8) from level 11.

**Comment by uaktags** [comment]
Found an example with me attacking user 84, Kalego.


```
0|OT  |  ⨯ src/models/BattleResult.tsx (51:24) @ units
0|OT  |  ⨯ TypeError: units is not iterable

0|OT  |   page: '/api/attack/[id]'
0|OT  | }
0|OT  |   49 |     const killedUnits: BattleUnits[] = [];
0|OT  |   50 |
0|OT  | > 51 |     for (const unit of units) {
0|OT  |      |                        ^
0|OT  |   52 |       const unitCasualties = Math.min(unit.quantity, casualties - distributedCasualties);
0|OT  |   53 |       distributedCasualties += unitCasualties;
0|OT  |   54 |       unit.quantity -= unitCasualties;
0|OT  |  POST /api/attack/84 500 in 28ms
```

**Comment by Revenate39** [comment]
Centurion 
NorthernBack
KingJoshya
Are some users I'm having the issue with, I haven't found someone who I can attack who is a lower lv

**Comment by uaktags** [comment]
Gotcha, give it a try again when you're ready. Found the issue, happens because they didn't have defense units and I made a recent change to the collateral units that get killed

**Comment by uaktags** [comment]
Now, citizens, workers, spies, and sentries are at risk of death if the defender has no defense units.

**Comment by Revenate39** [comment]
Back to working normally, love your work!

**Comment by uaktags** [comment]
Thanks man, still getting the math right on the collateral but it's coming together! We're getting closer and closer every few days.
