### ISSUE TITLE
Attack System Revision - 6/12/24

### ISSUE THREAD

**Issue by uaktags** [OpenThrone/OpenThrone#115]
I've made a few small changes to the attack system following the run-on deaths that attackers were taking and the overwhelming casualties that the workers/citizens were taking. 

This revision leaves Workers and Citizens as collateral, but only 25% of them and only if Defense is less than 25 of the total of Defense + Workers + Citz. 

We're going to keep monitoring the system as it is right now.

**Comment by Revenate39** [comment]
I might of missed this, but at the moment attacking appears to be limited at 5 attacks per 24hr's regardless of who you attack.

I was only able to attack 5 different users once each today before receiving the 'Failed to execute attack. You have attacked too many times in the last 24 hours.' prompt.

![Screenshot 2024-06-14 152800](https://github.com/OpenThrone/OpenThrone/assets/171521017/00350781-b9b0-4410-bd65-9024c275a4c1)

**Comment by JOHNNYGAZER** [comment]
![image](https://github.com/OpenThrone/OpenThrone/assets/170389243/9abd9466-c712-41aa-97df-58daef4462cb)

@Revenate39 I'm seeing something similar, but I was locked out of attacking after only 4 attacks. @uaktags I'm unable to attack Centurion for a 5th time or attack any other players.

**Comment by uaktags** [comment]
Thanks guys, looks like a recent change broke it. I'm testing the fix and will push to the live version soon

**Comment by uaktags** [comment]
Closing this as a new iteration will be pushed out shortly
