### ISSUE TITLE
Armory Unit Totals

### ISSUE THREAD

**Issue by NunosDC** [OpenThrone/OpenThrone#116]
Only Type 1 units are in the total maybe it could be all unit types or even separated out in to each type if that is what the community wants.

![image](https://github.com/OpenThrone/OpenThrone/assets/146961378/ffd89a0f-b7fd-4af6-83a8-85cdfeb03d1e)

**Comment by uaktags** [comment]
I don't recall any changes but an you double check that this is still an issue?

![image](https://github.com/OpenThrone/OpenThrone/assets/893684/97bc2e3a-459b-4844-806c-2e3f2d4b0e94)

![image](https://github.com/OpenThrone/OpenThrone/assets/893684/46c2603d-950c-49eb-b8d4-5cae0c14da9b)

**Comment by NunosDC** [comment]
I think you fixed it.
