### ISSUE TITLE
Unable to purchase structure upgrade

### ISSUE THREAD

**Issue by Revenate39** [OpenThrone/OpenThrone#118]
Found a strange little bug, which is a result of me missing buying the first Clandestine Upgrade (Rope Training), and now that I'm lv10 and have purchased the 'Town' upgrade it will only let me purchase 'Basic Stealth Training'. However when I select 'Buy', I get the error: 'Invalid Spy Upgrade Level to purchase upgrade'.

Hopefully the screenshot below makes a bit more sense

![Screenshot 2024-06-16 203511](https://github.com/OpenThrone/OpenThrone/assets/171521017/b4b4c51c-a1d0-4283-b9e3-aa7b26ad03c2)

**Comment by Dimez123** [comment]
I have the same thing, for about 3 weeks now, didnt care since it was spy stuff, but if this ticket is up, I'll add mine ontop of it.

![123](https://github.com/OpenThrone/OpenThrone/assets/132112018/52a26ee7-9ba2-411c-92e3-a5b9da9323e9)
