### ISSUE TITLE
F5 refresh page error

### ISSUE THREAD

**Issue by Dimez123** [OpenThrone/OpenThrone#119]
Refreshed stat page to check when I hit max recruitment and it gives this error. I can X out of it and still see the updated page, but figured this counts as reportable.

Unhandled Runtime Error
Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used
See more info here: https://nextjs.org/docs/messages/react-hydration-error

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

...
  ...
+  6/16/2024, 5:54:51 PM
-  6/16/2024, 6:54:51 PM
Call Stack
React
throwOnHydrationMismatch
node_modules/react-dom/cjs/react-dom-client.development.js (10606:1)
prepareToHydrateHostTextInstance
node_modules/react-dom/cjs/react-dom-client.development.js (10781:1)
completeWork
node_modules/react-dom/cjs/react-dom-client.development.js (26085:1)
completeUnitOfWork
node_modules/react-dom/cjs/react-dom-client.development.js (28574:1)
performUnitOfWork
node_modules/react-dom/cjs/react-dom-client.development.js (28378:1)
workLoopConcurrent
node_modules/react-dom/cjs/react-dom-client.development.js (28353:1)
renderRootConcurrent
node_modules/react-dom/cjs/react-dom-client.development.js (28309:1)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom-client.development.js (27138:1)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (249:1)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (218:1)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (525:1)

**Comment by uaktags** [comment]
Issue has been resolved, was due to a misconfiguration on the deployment script
