### ISSUE TITLE
Attack caused full fort damage.

### ISSUE THREAD

**Issue by Dimez123** [OpenThrone/OpenThrone#120]
Repaired fort to 500 last night, went from 500 to 0 in one attack.

GG

**Comment by uaktags** [comment]
Thanks for closing, guess there's nothing to be looked at.

**Comment by NunosDC** [comment]
It would be the attack below.

![image](https://github.com/OpenThrone/OpenThrone/assets/146961378/5a468e10-0d77-4c42-a02e-b5fdfeb14336)

**Comment by uaktags** [comment]
this is resolved with 0e9c414
