### ISSUE TITLE
6/18 Attack function

### ISSUE THREAD

**Issue by uaktags** [OpenThrone/OpenThrone#121]
A new version of the attack function is going into play shortly. Changes involve having a killing strength and defense strength to each unit and item. Still need to add some to Forts and Battle Upgrades

**Comment by Revenate39** [comment]
A couple bits I have noticed in my attacks today, the first is that once I select how many turns to attack with and click 'Submit' nothing happens. The attack goes through, and appears in my 'War History' but the attack log result doesn't automatically appear on screen like it used to after clicking submit.

The second is best described with a screenshot, but in short, I would normally think that more offence than defence would be a 'winning' formula.

![Screenshot 2024-06-20 082815](https://github.com/OpenThrone/OpenThrone/assets/171521017/b576a80c-6404-4d1f-8064-e1737f6cb2bd)

**Comment by uaktags** [comment]
Taking a look!

[Thinking out loud] 
So with the new attack functions, we've added Killing Strength and Defense Strength to items and units. So items have either a +Defense or +Offense bonus, but they also have a breakdown of killing strength vs defense strength
```
{
    name: 'Dagger',
    usage: 'OFFENSE',
    level: 1,
    bonus: 25,
    cost: 12500,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 20,
    defenseStrength: 5
  },
  ```
  Right now though, we decide winning vs losing of a battle based on this equation:
  ```
  if (PhysOffToDefRatio >= 1) {
    // Attacker Wins
    result.Result = 'Win';
    result.Experience.Attacker = Math.round(
      (140 + PhysDefToOffRatio * 220 + OffUnitRatio * 100) * AmpFactor
    );
    result.Experience.Defender = Math.round(
      (20 + PhysDefToOffRatio * 40 + DefUnitRatio * 15) * AmpFactor
    );
  } else {
    // Defender Wins
    result.Result = 'Lost';
    result.Experience.Attacker = Math.round(
      (80 + PhysOffToDefRatio * 50 + OffUnitRatio * 25) * AmpFactor
    );
    result.Experience.Defender = Math.round(
      (30 + PhysOffToDefRatio * 45 + DefUnitRatio * 20) * AmpFactor
    );
  }
  ```
  So if the Offense to Defense ratio is greater than or equal 1, then the attacker wins, but if its less the Defender wins. In this case we'd expect Reveante to win due to Offense being 2.2mil vs 1.9mil.
  
  But with the new killing strength/defense strength, we are calculating the ratio differently now:
  ```
  result.experienceResult = computeExperience(
      attacker,
      defender,
      attackerKS / (defenderDS ? defenderDS : 1) // PhysOffToDefRatio
    );
    ```
    So PhysOffToDefRatio is based on the KillingStrength of the attacker / the defender's defense strength.
    In this case, the values actually work out to this:
    ```
    attackerKS 918682 
    defenderDS 984919
    ```
    which in this case means that the PhysOffToDefRatio is .93 rather than 1+.
    
    So the winner *SHOULD* be fixed to being raw Offense / Defense, but the deaths should be calculated based on the Killing vs Defense scores.
    
    ---------
    
    Alright, should be a simple fix

**Comment by uaktags** [comment]
// 20240620111729
// https://alpha.openthrone.dev/api/attack/retest/1860

{
  "originalAttackerArmy": 14990,
  "originalDefenderArmy": 14603,
  "originalAttackerLosses": 20,
  "originalDefenderLosses": 30,
  "newSimulationAttackerArmy": 14990,
  "newSimulationDefenderArmy": 14603,
  "newSimulationAttackerLossesTotal": 20,
  "newSimulationAttackerLossesBreakdown": {
    "total": 20,
    "units": [
      {
        "level": 1,
        "type": "OFFENSE",
        "quantity": 2
      },
      {
        "level": 1,
        "type": "OFFENSE",
        "quantity": 2
      },
      {
        "level": 1,
        "type": "OFFENSE",
        "quantity": 2
      },
      {
        "level": 1,
        "type": "OFFENSE",
        "quantity": 2
      },
      {
        "level": 1,
        "type": "OFFENSE",
        "quantity": 2
      },
      {
        "level": 1,
        "type": "OFFENSE",
        "quantity": 2
      },
      {
        "level": 1,
        "type": "OFFENSE",
        "quantity": 2
      },
      {
        "level": 1,
        "type": "OFFENSE",
        "quantity": 2
      },
      {
        "level": 1,
        "type": "OFFENSE",
        "quantity": 2
      },
      {
        "level": 1,
        "type": "OFFENSE",
        "quantity": 2
      }
    ]
  },
  "newSimulationDefenderLossesTotal": 36,
  "newSimulationDefenderLossesBreakdown": {
    "total": 36,
    "units": [
      {
        "level": 2,
        "type": "DEFENSE",
        "quantity": 3
      },
      {
        "level": 2,
        "type": "DEFENSE",
        "quantity": 4
      },
      {
        "level": 2,
        "type": "DEFENSE",
        "quantity": 4
      },
      {
        "level": 2,
        "type": "DEFENSE",
        "quantity": 4
      },
      {
        "level": 2,
        "type": "DEFENSE",
        "quantity": 3
      },
      {
        "level": 2,
        "type": "DEFENSE",
        "quantity": 3
      },
      {
        "level": 2,
        "type": "DEFENSE",
        "quantity": 4
      },
      {
        "level": 2,
        "type": "DEFENSE",
        "quantity": 3
      },
      {
        "level": 2,
        "type": "DEFENSE",
        "quantity": 4
      },
      {
        "level": 2,
        "type": "DEFENSE",
        "quantity": 4
      }
    ]
  },
  "fortHPAtEnd": 452,
  "attackerWon": "Win"
}

So as expected, the win condition would be that Rev would have won, and the number of deaths between the two attacks would be similar (variances due to the randomness factors)

**Comment by uaktags** [comment]
Closing as this has been stable
