### ISSUE TITLE
No Combat Log While Attacking

### ISSUE THREAD

**Issue by JOHNNYGAZER** [OpenThrone/OpenThrone#128]
After submitting an attack against a player, the "How many turns?" dialog box does not go away and the battle log is not opened. It would be easy to accidentally attack one or more additional times without realizing the issue.

**Comment by uaktags** [comment]
"Internal Server Error"

somethings broken, wil take a look

**Comment by uaktags** [comment]
This is due to the change back from ISR to SSR 3a86f901e7af10d1cb6916ca17ba4997ab4495ec

Fix is done just needs to be pushed out shortly.
