### ISSUE TITLE
Training - Untrain isn't handling 75% rate and Conversion isn't working at all.

### ISSUE THREAD

**Issue by JOHNNYGAZER** [OpenThrone/OpenThrone#129]
Listed sell values are off. For tier 1 units it seems like there is no gold loss from untraining units, but for tier 2 units (knights and archers), you get the refund amount listed for tier 2 units instead, resulting in major losses.

Worker
Listed refund: 1,500
Actual refund: 2,000

Soldier
Listed refund: 1,125
Actual refund: 1,500

Knight
Listed refund: 7,500
Actual refund: 1,500

Guard
Listed refund: 1,125
Actual refund: 1,500

Archer
Listed refund: 7,500
Actual refund: 1,500

Spy
Listed refund: 1,125
Actual refund: 1,500

Sentry
Listed refund: 1,125
Actual refund: 1,500

**Comment by uaktags** [comment]
#130 also is part of this. So the untrain and conversions are not happening correctly.

**Comment by uaktags** [comment]
//train.ts
totalCost += (unitType.cost - ((uModel.priceBonus || 0) / 100) * unitType.cost) * unitData.quantity;

//untrain.ts
 totalCost += (unit.cost - ((uModel.priceBonus || 0) / 100) * unit.cost) * unitData.quantity;
 
 So we're missing the 75% difference.
