### ISSUE TITLE
No Conversion Refund

### ISSUE THREAD

**Issue by JOHNNYGAZER** [OpenThrone/OpenThrone#130]
When converting units from tier 2 to tier 1, the conversion UI shows a refund value, but it does not actually refund any gold. I noticed this when I accidentally mis-clicked and lost around 35mil gold converting the wrong way :)

Knight to Soldier Conversion
Listed refund: 6375
Actual refund: 0

Archer to Guard Conversion
Listed refund: 6375
Actual refund: 0

**Comment by uaktags** [comment]
I'm closing and merging this with #129. Looks like both issues are with training.
