### ISSUE TITLE
Display Defensive Unit Ratio in Training Center

### ISSUE THREAD

**Issue by JOHNNYGAZER** [OpenThrone/OpenThrone#145]
In the training center, in addition to the three tiles for "Untrained Citizens", "Gold On Hand", and "Banked Gold", I think that it would be helpful to have a tile for the percentage of your population that is trained for defense. 

Additionally, if the percentage is UNDER 25%, showing the percentage bolded and in red to give an indication that something needs attention would be cool. 25-30% in yellow since you could lose that margin in a few attacks, and 30%+ shows green.

Would love to hear other's thoughts on this!

**Comment by uaktags** [comment]
I'm definitely for this and it's a simple enough addition. I'll play with some ideas until I see others get posted. In addition to the tile, I think the training page needs contextual descriptions for the sections. This may make a suitable place to show, as the tile will be out of focus on a lot of screens.

**Comment by uaktags** [comment]
![image](https://github.com/user-attachments/assets/1fed8c76-6b9d-44cc-a63c-a953ccd6c3e2)
on hover/tooltip:
![image](https://github.com/user-attachments/assets/2791e853-eeda-4b65-93c2-4244bfa791f4)
