### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Shigamonwai** [OpenThrone/OpenThrone#155]
![Screenshot 2024-08-03 031722](https://github.com/user-attachments/assets/708d4326-a1a9-4290-898b-30d82a639205)

Getting "Invalid username or password" when trying to log in on both mobile & pc/browser.

**Comment by uaktags** [comment]
Thanks, taking a look!

**Comment by uaktags** [comment]
So i'm not getting anything in the logs other than the failed username/password message as well. We may need to do a password reset or ping me on discord and we can test on the test server whats going on by turning on further debugging

**Comment by Shigamonwai** [comment]
It's strange, on my computer I'll already be logged in so it's no biggie for there but on mobile it won't go through. I'll try resetting password and see if I can get through.
-------- Original message --------From: Tim Garrity ***@***.***> Date: 8/5/24  8:05 AM  (GMT-06:00) To: OpenThrone/OpenThrone ***@***.***> Cc: Shigamonwai ***@***.***>, Author ***@***.***> Subject: Re: [OpenThrone/OpenThrone] Login issues (Issue #155) 
So i'm not getting anything in the logs other than the failed username/password message as well. We may need to do a password reset or ping me on discord and we can test on the test server whats going on by turning on further debugging

**Comment by Shigamonwai** [comment]
Is there supposed to be any kind of dialogue returned when you submit your email for password reset? I'm not getting anything after hitting the submit button and no email yet. 😬
-------- Original message --------From: shigamonwai ***@***.***> Date: 8/5/24  1:57 PM  (GMT-06:00) To: OpenThrone/OpenThrone ***@***.***> Subject: Re: [OpenThrone/OpenThrone] Login issues (Issue #155) It's strange, on my computer I'll already be logged in so it's no biggie for there but on mobile it won't go through. I'll try resetting password and see if I can get through.-------- Original message --------From: Tim Garrity ***@***.***> Date: 8/5/24  8:05 AM  (GMT-06:00) To: OpenThrone/OpenThrone ***@***.***> Cc: Shigamonwai ***@***.***>, Author ***@***.***> Subject: Re: [OpenThrone/OpenThrone] Login issues (Issue #155) 
So i'm not getting anything in the logs other than the failed username/password message as well. We may need to do a password reset or ping me on discord and we can test on the test server whats going on by turning on further debugging

**Comment by uaktags** [comment]
![image](https://github.com/user-attachments/assets/c0da2a6a-cd72-408e-81b7-87cd16feb0b8)

You're supposed to get this, admittedly bad UI page

**Comment by uaktags** [comment]
I'm wondering if we have a mobile issue. You're getting unable to login with mobile AND you're failing to fire off the form submission on mobile.

- Browser/OS you're using (wondering if compatibility may be an issue with the UX and the browser/aspect ratio)
- Using Wifi or Mobile Data (wondering if DNS may be a factor)
- Tested in both regular and incognito (just curious)

I'll see if i can't replicate

**Comment by Shigamonwai** [comment]
Sure, Browser - Chrome, OS - Android 14.Have tested on both mobile data & wifi with same issue.Just tried it on incognito mode and got the same result.
-------- Original message --------From: Tim Garrity ***@***.***> Date: 8/5/24  3:12 PM  (GMT-06:00) To: OpenThrone/OpenThrone ***@***.***> Cc: Shigamonwai ***@***.***>, Author ***@***.***> Subject: Re: [OpenThrone/OpenThrone] Login issues (Issue #155) 
I'm wondering if we have a mobile issue. You're getting unable to login with mobile AND you're failing to fire off the form submission on mobile.

Browser/OS you're using (wondering if compatibility may be an issue with the UX and the browser/aspect ratio)
Using Wifi or Mobile Data (wondering if DNS may be a factor)
Tested in both regular and incognito (just curious)

I'll see if i can't replicate

**Comment by Shigamonwai** [comment]
Ahaha it's not all that terrible
-------- Original message --------From: Tim Garrity ***@***.***> Date: 8/5/24  3:09 PM  (GMT-06:00) To: OpenThrone/OpenThrone ***@***.***> Cc: Shigamonwai ***@***.***>, Author ***@***.***> Subject: Re: [OpenThrone/OpenThrone] Login issues (Issue #155) 
image.png (view on web)
You're supposed to get this, admittedly bad UI page

**Comment by uaktags** [comment]
Interesting, tested with Chrome, Brave, and IceRaven without issue on A14 (well without your issues, i found numerous UI issues).

I'm going to send you a message on discord for our private dev url to test there.
