### ISSUE TITLE
Recruitment

### ISSUE THREAD

**Issue by LordMike13** [OpenThrone/OpenThrone#158]
Hello, I have not been able to recruit in the automatic mode, more than 24 hours have passed and I get the following message "ERROR
"No valid users available for recruitment".
I am from Mexico UTC/GMT time -6 hours. OT user "LordMike13"

Thank you and greetings, congratulations on this project, I will be playing until the end...
![imagen_2024-08-06_144505880](https://github.com/user-attachments/assets/f509f24b-78e6-4038-8db1-6809785667cc)

**Comment by uaktags** [comment]
Thanks for the bug report and welcome!
Just wanted to confirm, you've reloaded the page or clicked the Restart Recruiting? It does look like you should be able to get users.
If you can, try going to this page:
https://openthrone.dev/api/recruit/getRandomUser

If you could, just confirm that the result is something akin to
```
{
"totalLeft": 590,
"totalPlayerCount": 118,
"maxRecruitsExpected": 590
}
```
You can also check on https://openthrone.dev/api/recruit/getRecruitHistory to see what was the last results we have recorded.

**Comment by LordMike13** [comment]
Hi, I have not been successful, Sunday night was my last recruitment and with this time 48 hours have passed without being able to recruit, let's hope it can be solved. If I'm doing something wrong, please let me know. Fraternal greetings and thanks
![image](https://github.com/user-attachments/assets/6fd17b85-b844-49dc-aadc-ada25133f3b6)

**Comment by LordMike13** [comment]
Hello, good day, yes friend, I have refreshed, I deleted cache, I have even
used other addresses I.

**Comment by uaktags** [comment]
What happens when you go to:
https://openthrone.dev/api/recruit/getRandomUser
and 
https://openthrone.dev/api/recruit/getRecruitHistory

**Comment by LordMike13** [comment]
Thanks, I'll check it out.

**Comment by uaktags** [comment]
Found the issue to be related to a broken Prisma DB binding. Had to rerun prisma generate on the prod server
