### ISSUE TITLE
External Recruiter

### ISSUE THREAD

**Issue by NunosDC** [OpenThrone/OpenThrone#167]
Something is causing the external recruiter to miscount or apply auto recruit counts.
First I was able to click myslef 5 times noted in 1 and 2 that seems to work.... After this I tried to click two more accounts that haven't clicked themselves and I presume haven't been clicked 25 times by others and received the results in capture 3 and 4.
![Capture03](https://github.com/user-attachments/assets/b96cb101-c2ab-414d-9f57-e70839923b3f)
![Capture04](https://github.com/user-attachments/assets/162c2870-007d-4348-9553-4d8be1ea99da)

![Capture01](https://github.com/user-attachments/assets/10e3ef1e-a18f-4880-ae20-07bd0f417c79)
![Capture02](https://github.com/user-attachments/assets/29b6236b-adcf-4a5d-a2f7-12f1fb5990bf)

**Comment by uaktags** [comment]
fixed with 69b3f31 and e53af51
