### ISSUE TITLE
"Flickering" Stats on Overview Page

### ISSUE THREAD

**Issue by JOHNNYGAZER** [OpenThrone/OpenThrone#171]
When I initially load the "Overview" page, it shows my Offense stat as 6,503,841 an my Defense stat as 30,166,136. After a few seconds, it will change to 6,506,081 and 30,171,680 respectively.  If I hit the refresh stats button in the left panel, it will change to 6,507,201 and 30,169,832. Refreshing the page does not return the the initially displayed values, but if I switch to any other tab in the UI and switch back, it shows the values from my first sentence. This is 100% reproducible.

**Comment by uaktags** [comment]
Seems to only be reproducible on larger accounts. Not reproducible on numerous low level ones. State management issue, need to look into the loading/rerending prior to updating the state, too many calculations happening.

**Comment by JOHNNYGAZER** [comment]
@uaktags Could this be something to do with battle upgrades? Seems like if it's only on higher level accounts this could be the cause. I don't remember EXACTLY when this started happening, but it was close to the time that I unlocked and purchased battle upgrades.

If you want to repro on my account, wipe battle upgrades and check again, go for it.

**Comment by uaktags** [comment]
It's a combination of all of the calculations. As we start getting into higher levels, we're calculating multiple levels of battle upgrades, units, and items. My thought process is that this calculation is taking time and is not waiting until the final calc before displaying (state management issue).

**Comment by Revenate39** [comment]
Looks like you guys are all over it, video below if you wanted an example

https://github.com/user-attachments/assets/6812db47-a013-497c-9eab-7b8e2482f9b6

**Comment by uaktags** [comment]
Fixed
