### ISSUE TITLE
Archer sell value incorrect

### ISSUE THREAD

**Issue by Revenate39** [OpenThrone/OpenThrone#172]
I believe selling archers is the same value as guards, i.e 1,125 instead of the advertised 7,500

**Comment by uaktags** [comment]
Archers are level 2 and guards are level 1, giving them different sell values and buy values.

**Comment by Revenate39** [comment]
> Someone clarified that the issue is: "When untraining an archer, it only rewards the 1125 gold and not the 7500. I think that's what was being posted".
> 
> Reopening to take a look

Correct!
'sniffles' realizes OT short changed me an estimated 310,462,500 from the above

**Comment by uaktags** [comment]
Patch is done, will be uploaded shortly
