### ISSUE TITLE
Error uploading file. Error uploading to S3

### ISSUE THREAD

**Issue by camarao69** [OpenThrone/OpenThrone#173]
I'm unable to upload an avatar because of this error. "View Profile" button on Profile does not work and "Save Profile" does not save when i wright on comments.

**Comment by uaktags** [comment]
Going to attach this to #150 and close as its the same issue. Thanks for the creation.

Comments will be updated shortly to show they're not yet implemented and will later be renamed to Profile Bio

**Comment by camarao69** [comment]
Thank you , I was trying to do that.
