### ISSUE TITLE
Community stats page

### ISSUE THREAD

**Issue by Revenate39** [OpenThrone/OpenThrone#177]
I'm not sure what exactly the 'Top 10 Attacks by Total Casualties in last 7 days' is calculating, however there are currently eight 0 stat battles, and only two with casualty numbers.

I will use my own attack logs as an example, but I know yesterday I had offensive kills on MarkTraceur, TylerNight, and luK (maybe some others). I would of thought they would show up, along with other users attacks on each other instead of the eight 0 battles.

![Screenshot 2024-08-21 091948](https://github.com/user-attachments/assets/bb6fe1aa-96de-4cee-9319-1e55831a1f50)

**Comment by MarkTraceur** [comment]
Good catch! #178 should fix this.
