### ISSUE TITLE
Overall rank displaying differently

### ISSUE THREAD

**Issue by Revenate39** [OpenThrone/OpenThrone#186]
I promise I wont bring up anything else around rank for a week after this!

I've noticed a couple accounts displaying different ranks on their profile page compared to the attack page, there are 3 accounts on the first page. luK, Revenate, and Bronze_Mantis, see below screenshots.

![Screenshot 2024-08-22 144512](https://github.com/user-attachments/assets/882a9560-d359-4ae8-9197-745f4491097a)
![Screenshot 2024-08-22 144730](https://github.com/user-attachments/assets/71bbcf6b-d954-41e4-bca3-1945bd2f2ad2)

**Comment by uaktags** [comment]
Interesting, the way we show the OR happens on the fly which is very intensive and inefficient. Long ago, i added rank to the users db but felt that it wasn't ready to use. Months later, we're seeing that pain. I'll start working on the fix

**Comment by uaktags** [comment]
fixed!
