### ISSUE TITLE
Issue with attack page filter

### ISSUE THREAD

**Issue by Revenate39** [OpenThrone/OpenThrone#188]
Off the back of #186, the ranking filter is not operating correctly. Selecting the 'Rank' filter changes the numbers but not the users

**Comment by uaktags** [comment]
damn, must of missed that.

**Comment by uaktags** [comment]
fix is being tested, and should go live within the hour. Thanks

**Comment by Revenate39** [comment]
Something weird is going on again
![Screenshot 2024-08-27 163005](https://github.com/user-attachments/assets/7ffa5406-0cff-4d3a-bc4a-383225efcf2d)
