### ISSUE TITLE
Additional way to navigate the attack players browsing page using Page "1, 2, 3,.... n",

### ISSUE THREAD

**Issue by Figwumberton** [OpenThrone/OpenThrone#190]
But anyway could you imagine if there was a 1000 players and you want to check certain pages. It would take a while. Plus its like the old game if im not mistaken. Pitch is over. Dont know how github works. someone told me to use it.

**Comment by NunosDC** [comment]
Great idea. From what I remember in DT you could select how many people to show per page and you could select pages by number.

**Comment by uaktags** [comment]
I never quite understood the "go to page" functionality, but that should be pretty simple. We already track the pages in the url so we should be able to test out adding a goto feature.

For the pagination there's a few variations that I kinda like and wouldn't mind some feedback.
https://mantine.dev/core/pagination/
Specifically, I like the idea of:
[<] [1]...[6][7][8

**Comment by NunosDC** [comment]
I kinda like the page numbers that you listed [<] [1]...[6][7][8]...[20] [>]. 
I don't understand the two properties of Siblings and Boundaries but perhaps these could be tied to the attack range your account can attack +5 and minus -5 levels from you?

I also would still love to see a drop down that allows you to pick how many to display per page say Item 1 = 10, Item 2 =25, item 3 = All In Range.
Not sure that is possible in mantine and not sure what to search for in their documentation to find what they offer.

**Comment by Figwumberton** [comment]
[1],[2],[3].....[20] is a great start I think.

**Comment by uaktags** [comment]
![image](https://github.com/user-attachments/assets/3dfda4a1-dc0b-425e-b557-1b6b0d0f1ee2)
![image](https://github.com/user-attachments/assets/a5232e14-ec9a-4a04-91c2-9ade4c88a76a)
![image](https://github.com/user-attachments/assets/14db7d83-87c6-4eac-9723-5b11742ae4a1)

quick and dirty test, makes it easy to get from 1 end to the other, and there's 1 page to your left and right always available to see. 


Regarding goto page.
This is DT's source implementation:
![image](https://github.com/user-attachments/assets/3d39e794-1958-4859-bdb3-6f7b1311635b)

I'm personally of the opinion that "Attack User" is redundant, as you can either click on their name as is or you can type in to the Search on the left hand side. However, we are missing buttons in the top, a total page count, etc

![image](https://github.com/user-attachments/assets/964f152b-741b-455f-aadd-bc9655442fc0)
Some combination of it all:
![image](https://github.com/user-attachments/assets/5d4ac511-7e23-4b57-ae4d-9788d66c7fbf)

**Comment by NunosDC** [comment]
I kinda like that
![image](https://github.com/user-attachments/assets/9464dacd-f351-41bb-a656-d3c6da50dd1b)

**Comment by uaktags** [comment]
@NunosDC 
regarding a selector for showing rows per page:
![image](https://github.com/user-attachments/assets/88d5167a-3c9c-4305-9354-ee677ab5d68c)

**Comment by uaktags** [comment]
This is what the page would look like with all incorporated

![image](https://github.com/user-attachments/assets/fbae9571-07dd-48a5-89c6-0a6e11a1da66)

**Comment by NunosDC** [comment]
That looks good to me and can scale as needed.

**Comment by uaktags** [comment]
@Figwumberton, any opinions on this implementation for the suggestion?
