### ISSUE TITLE
Battle Report Style Change

### ISSUE THREAD

**Issue by Dragonsoulj** [OpenThrone/OpenThrone#206]
Any way we can flip the direction of the battle report reveal to follow language style? Left to Right languages go Left to Right and Right to Left languages go Right to Left? This way it reveals parts you can start reading as the letters come into view.

**Comment by uaktags** [comment]
Simple enough change. I'll get to it later tonight if mark doesn't, just need to finish on my current branch.

```
  staggerDirection: 1, // 1: LTR  -1: RTL
```
When i18n support is made, we can have a condition based on text direction as mentioned above.

**Comment by MarkTraceur** [comment]
All yours, mate, I'm pretty beat!
