### ISSUE TITLE
Defensive stat variance

### ISSUE THREAD

**Issue by Revenate39** [OpenThrone/OpenThrone#211]
A nice quick example here hopefully. luK attacked me a couple times today and i'm getting a variance in my Defence stats on the defence log (2,421,049) and my overview page (3,184,443). 

Okay I lied it wont be as quick as I liked, the third snip shows two defensive wins, whilst my overview page 'Defends Won' shows 1.

![Screenshot 2024-08-29 132442](https://github.com/user-attachments/assets/73af917c-926b-43ce-8280-8b54724eb6a6)
![Screenshot 2024-08-29 132521](https://github.com/user-attachments/assets/66d514fd-e796-42dc-aaa5-bec428d7196d)
![Screenshot 2024-08-29 132635](https://github.com/user-attachments/assets/72dde654-aa79-41db-a350-7960233d6e3f)

**Comment by uaktags** [comment]
Hmm, interesting. 
| stat | type    | subtype |
| ---- | ------- | ------- |
|      | DEFENSE | LOST    |
|      | SENTRY  | WON     |
| 232  | OFFENSE | WON     |
| 44   | SPY     | WON     |
| 5    | OFFENSE | LOST    |
| 1    | DEFENSE | WON     |

so yea its totally not incremented in the db, im thinking there may be a related bug with #213
