### ISSUE TITLE
Unintelligent Battle Upgrade Usage

### ISSUE THREAD

**Issue by JOHNNYGAZER** [OpenThrone/OpenThrone#216]
I noticed today that when I bought more Catapults my defense didn't increase. I realized that this was due to me still having more Guard Towers than I need. Once I sold some Guard Towers, I saw the anticipated increase in my defense. I'm unsure on if this applies to normal armory equipment as well or not.

**Comment by uaktags** [comment]
What's the intelligent way?

**Comment by NunosDC** [comment]
Did you test to see if it applied to the armory? Typically if you can post some screen captures of the issue and keep each issue separated to it's own post it will be easier for us to address them.

**Comment by uaktags** [comment]
Closing this as MAYBE related to #212 . 

But i'll mention this, don't just drop something as "unintelligent" and not provide an intelligent solution. The first sentence makes it sound like you're reporting a bug, that you did something and something you expected to happen didn't happen. The second is a concession that you had more of one item that used up units than the other and you saw the math work (so no bug?). The 3rd is a concession that you're unsure if it applies to something else, but not quite listing out WHAT applies to something else.

If the question is whether a unit can be used by 2 different Battle Upgrades, the answer is no, it's limited on purpose and has an intelligent reason for it.
