### ISSUE TITLE
Family recruit link problem

### ISSUE THREAD

**Issue by camarao69** [OpenThrone/OpenThrone#238]
Hello there must be something wrong with the player (recruit) link system, I'ts 6 days in a row (at least) that I can't recruit a player .The message I recieve is always the same "You can only recruit a player up to 5x in 24 hours"

**Comment by camarao69** [comment]
> If you're trying to click the link with the same IP then you're going to hit the 5x limit.

It happens over diferent IP's

**Comment by uaktags** [comment]
> > If you're trying to click the link with the same IP then you're going to hit the 5x limit.
> 
> It happens over diferent IP's

I need more information man, you're giving me close to nothing to work with.

Are you logged in as a player?
If so, what player id
Are you trying to click another player? If so, id
Is it happening with all of your accounts? 

Try to give me a way to reproduce what it is you're doing so we can try to narrow down the issue. 2ips? 4ips?

**Comment by camarao69** [comment]
> > > If you're trying to click the link with the same IP then you're going to hit the 5x limit.
> > 
> > 
> > It happens over diferent IP's
> 
> I need more information man, you're giving me close to nothing to work with.
> 
> Are you logged in as a player? If so, what player id Are you trying to click another player? If so, id Is it happening with all of your accounts the same or is it different for different ones? Can you click the links before you start the auto-recruiter but not after?
> 
> Try to give me a way to reproduce what it is you're doing so we can try to narrow down the issue. 2ips? 4ips?
> 
> The current limits are: 5x per logged in player to another player and 5x per logged out user per IP to a player.
> 
> So you can click your own link 5x logged in and 5x logged out by the same IP.
> 
> If you use the autorecruiter, you are using the 5x logged in limit automatically.

Sorry I'm trying to track down the issue to , but today I as able to recruit even from the same IP from 2 diferent acounts myself .I may have logged in over the same IP the othertimes (but not recruit)
Tomorow I'm going to test again and I will post here what heppened

**Comment by camarao69** [comment]
Today I was able to do the (Link System) recruit ( over the same IP), don't know if you changed anything but it worked.

**Comment by uaktags** [comment]
https://github.com/OpenThrone/OpenThrone/commit/df70c8d94d30c8d4e6d0c7c332ecf763d95e7ec9

We fixed the external recruiter 6days ago, before then, you couldn't recruit properly logged out. So no other changes went into effect since.
