### ISSUE TITLE
Attack page filters

### ISSUE THREAD

**Issue by Revenate39** [OpenThrone/OpenThrone#240]
The Attack page filters for 'Gold', 'Population', and 'Level' appear to be around the wrong way.
Screenshots below for examples.

![Screenshot 2024-09-19 083324](https://github.com/user-attachments/assets/607bf297-2a0b-4b66-b3f5-c0569612c9a6)
![Screenshot 2024-09-19 083228](https://github.com/user-attachments/assets/9a177cd4-1c4b-4cdb-831b-6c03ce9b9360)
![Screenshot 2024-09-19 083305](https://github.com/user-attachments/assets/e47ad685-1da3-49b3-b3bd-36539ff38a84)

**Comment by NunosDC** [comment]
If you hover over the heading again you should see an arrow pointing Up in your case so click again and it should point down and change the filter order.

**Comment by NunosDC** [comment]
In your first picture you are sorting by Level from highest to lowest so that looks right to me. Picture two you are sorting gold from most to least  so that looks right also. And in the final picture I see population being sorted up from lowest to highest.

**Comment by Revenate39** [comment]
It could just be me then, but I would expect the highest Lv i.e luK to be the highest rank which is 1, however it's showing as 125.
Similarly Johnny has the most gold and I would expect the rank to reflect the highest rank.
In the last example I would expect the opposite, Eutychus has the lowest pop, so I would think his pop rank would be the lowest '125'.

**Comment by NunosDC** [comment]
Overall rank is calculated diferently then highest level. Your first picture has a arrow on the level header pointing down which means you are sorting the list by level from the highest descending or down to the lowest. So rank has nothing to do with the list sort you have applied.

**Comment by Revenate39** [comment]
I'm guessing this is a just me thing as I agree with what your saying, apart from 'rank has nothing to do with the list sort you have applied'. As it does, the 'Rank' column changes depending on what list you choose to filter. Each list has an individual 'Rank' which is separate from the others. Apart from OR and Level, they appear to mimic each other.

I will use Taco's account as it has some better variances in ranks than my own.
OR = 30 (This list filter is correct (in my mind it's correct))
Gold rank = 121 (This in my mind should display as 5)
Population = 112 (This in my mind should display as 14)
Level = 96 (This in my mind should display as 30)

What I'm trying to say is that Taco's account has the 14th highest population and the attack page list for Population rank currently displays his account as '112', where I would expect the rank column to be around the other way and display his rank as '14'

In it's simplest form if someone has the most gold on hand (and your using the 'Gold' list filter) I would imagine the left most column 'Rank' would display '1', not '125'. This is to display their account is ranked number 1 for having the most gold on hand, the account with the second most gold on hand gets the rank of '2' and so on. This has nothing to do with OR, or which way the arrows face.

Similarly when using the population filter the account with the most population would have the left most column 'Rank' display a '1', and the account with the lowest population would be the opposite and display '125'.

**Comment by uaktags** [comment]
Got it, yea i see what you're saying, so it appears that the ranks when you sort by the other columns, is actually reversed. 

If I sort by Rank, i'm actually sorting by OR (which is currently still XP heavy so its similar to Level) from highest to lowest (desc) which is actually lowest to highest in terms of "rank" number
![image](https://github.com/user-attachments/assets/b03a85a5-18e6-47c1-812e-e2f42cd70782)
and then asc which is actually lowest overall rank (the highest number displayed) to the highest rank (lower number)
![image](https://github.com/user-attachments/assets/9ea85c77-e9fb-4bd9-8566-3b96d95aa932)


For gold, we would assume things to work a bit more correctly, but we're saying that they dont right now:
Gold Ascending should be lowest amount of gold to highest amount of gold
![image](https://github.com/user-attachments/assets/2e7cb0f2-c2a2-48ad-8884-a806d9b1e3d5)
and descending
![image](https://github.com/user-attachments/assets/a1a9cd32-2453-4718-bcf0-36ef36a4760f)

Instead, I think you're expecting/suggesting this:
Desc
![image](https://github.com/user-attachments/assets/b28d8e92-9576-4c95-9fae-29e464e2f55a)
Asc
![image](https://github.com/user-attachments/assets/c9e788e4-d5c3-429e-abd5-f60d577a4676)

**Comment by uaktags** [comment]
Take a look at #241 to see the proposed changes

**Comment by Revenate39** [comment]
Couldn't of said it better myself Taco 👍
