### ISSUE TITLE
Levels system not working

### ISSUE THREAD

**Issue by GroupTherapyPT** [OpenThrone/OpenThrone#246]
When I try to add a proficiency point to a stat and then proceed to save changes nothing ends up happening.

**Comment by uaktags** [comment]
Hmm, not reproducing an issue on any of my accounts. Can I get your user id and i'll see if there's anything account specific that could be breaking the logic.

**Comment by GroupTherapyPT** [comment]
Absolutely.

https://openthrone.dev/userprofile/153

**Comment by uaktags** [comment]
Patch is live now, you should be able to update your levels

**Comment by GroupTherapyPT** [comment]
Working fine now.

**Comment by uaktags** [comment]
Awesome, thanks for the confirmation and posting the issue. Going to close the ticket.

Welcome to OT.
