### ISSUE TITLE
Battle Upgrades Not Calculated in Wealth

### ISSUE THREAD

**Issue by JOHNNYGAZER** [OpenThrone/OpenThrone#253]
Battle upgrades don't appear to factor in wealth calculations. My wealth increased significantly after selling battle upgrades.

**Comment by Revenate39** [comment]
Can confirm battle upgrades sell at 100%

**Comment by uaktags** [comment]
Are you talking about on community/stats or somewhere else?

**Comment by Revenate39** [comment]
Yeah on the stats page, I would say I'm missing about half my net worth
