### ISSUE TITLE
No deaths even when fort is at 0 (same level)

### ISSUE THREAD

**Issue by camarao69** [OpenThrone/OpenThrone#255]
Hello, this is not good for the game, I have been in a little war with LordMike  he decided to sell all his defence and started to kill my population, I'm not against this, all my defenders died in the process at least to get even and as He has no defense now, I attacked him and noticed there were no deaths by him, I thought maybe he has to have his fortification down to 0 to achieve deaths on other troops/citizens whatever. So I asked other players to take his fortification down. After that I attacked with my account only to find out the same result.

![image](https://github.com/user-attachments/assets/19d6553f-b90b-45c6-bea4-dabe82a04765)

**Comment by uaktags** [comment]
He didn't have any units for you to kill. This has been referenced numerous times about which units are at risk and which aren't. Use an intel report to scope out their units base. No issue here.
