### ISSUE TITLE
Cannot View Next Page for Defense Log

### ISSUE THREAD

**Issue by JOHNNYGAZER** [OpenThrone/OpenThrone#259]
I seem to have been attacked a lot today, but when attempting to lick my wounds and check the defense logs, I am unable to proceed passed the first page of defense logs. When hovering over the "next" button for attack logs, I see a pointing finger cursor indicating that this is a clickable link. When I hover over the "next" button for the defense log, the cursor does not change. Clicking on the button does nothing and there are no errors or events in the dev console of Chrome. 

I did also notice that there are only 4 items in my defense log when I believe that the normal amount to display is 5 per page. I was attacked quite a lot today for some reason and have been enduring daily 5x10 attacks from Revenate for the last 7-10 days, so I would expect several pages of defense logs to be present :)

Unfortunately, when trying to capture a screenshot of the cursors it doesn't seem to include the cursor, but feel free to login to my account to check it.

**Comment by JOHNNYGAZER** [comment]
Forgot to add that this was occurring in Chrome, incognito mode in Chrome, and Microsoft Edge

**Comment by JOHNNYGAZER** [comment]
![def log](https://github.com/user-attachments/assets/457c62ce-2068-4246-9210-0233e7ca4fd3)

**Comment by uaktags** [comment]
Yea you have way more defense logs in the db than this. Not seeing any obvious bugs.
The defense logs don't show pages so there's no indication if the db is returning fragments or if there's only really 4 logs.

Patch being tested right now in dev
![image](https://github.com/user-attachments/assets/3ecf10d7-cefe-4c3f-894d-dcdeca75f2c6)
