### ISSUE TITLE
Verify you are human error

### ISSUE THREAD

**Issue by BronzeMantis** [OpenThrone/OpenThrone#33]
![nbbvv](https://github.com/uaktags/DarkCurse-nextjs/assets/150398391/b54416eb-c84e-4d67-a750-103e59a45809)
I ran into this issue whilst useing my recruit link and it happened when I pressed the verify you are human

**Comment by uaktags** [comment]
Looks like we'll need to capture when Cloudflare has an issue

**Comment by BronzeMantis** [comment]
I got this bug again, so I took a screenshot to see if it's any different.
![recruit](https://github.com/OpenThrone/OpenThrone/assets/150398391/9e64982a-8897-4d21-8302-1b5a9f33b663)

**Comment by uaktags** [comment]
Yea i'm seeing reports from others that use Cloudflare's Turnstile that this started popping up in november just like it is for us. We may need a new solution if this keeps up.

**Comment by BronzeMantis** [comment]
A bit more about the recruiter problem, I can only hope it's usefull or helpfull.
![collapse](https://github.com/OpenThrone/OpenThrone/assets/150398391/c61c3412-74fd-4f5a-9965-245952600d25)

**Comment by BronzeMantis** [comment]
More on the errors.
![rterror](https://github.com/OpenThrone/OpenThrone/assets/150398391/d2017f96-87aa-45a4-bceb-f2e9585016a9)

**Comment by uaktags** [comment]
This should be fixed for now. We'll still need to fix the auto-recruiter's reliance on Turnstile though.
