### ISSUE TITLE
Bizarre EXP Gains

### ISSUE THREAD

**Issue by wjrichardson84** [OpenThrone/OpenThrone#44]
![Screenshot 2023-12-13 220509](https://github.com/OpenThrone/OpenThrone/assets/150527682/32fd16d5-af0b-486b-9ce1-8b968b98c9b9)
![Screenshot 2023-12-13 220326](https://github.com/OpenThrone/OpenThrone/assets/150527682/0a809cdc-5e90-4a88-ae82-c5696de65172)
![Screenshot 2023-12-13 220902](https://github.com/OpenThrone/OpenThrone/assets/150527682/9fe98e3d-b16a-4495-a666-4e2ec0d04ce7)

I am currently level 4 and have only made 5 attacks total, the last 2 attacks I have remained level 4 and as you can see the experience I gained from the page before is way more than the 1,368 it said I had gained.

**Comment by uaktags** [comment]
Thanks, I'll take a look. Definitely bizarre and shouldn't be happening
