### ISSUE TITLE
Missing Gold Per Turn

### ISSUE THREAD

**Issue by BronzeMantis** [OpenThrone/OpenThrone#45]
I've been watching my gpt and it hasn't moved after consecutive turns. It appears that the turns haven't gone up either but I have to check first as it wasn't what I primarily was paying attention to. However the screenshot was taken before and after so it should be correct,

Before
![GPT](https://github.com/OpenThrone/OpenThrone/assets/150398391/8ae49a83-91ba-4602-87bc-6884e0289be4)
After
![GPT2](https://github.com/OpenThrone/OpenThrone/assets/150398391/bd0dc295-9532-4f56-acae-3f7035b7fde2)

**Comment by BronzeMantis** [comment]
Hmm gold and turns are appearing now, seems the issue has resolved itself.

**Comment by uaktags** [comment]
This may be due to a delay in when forceUpdate() fires. I'll have to come back to it. As of right now this is more of a front-end issue rather than a backend, as the backend will definitely have the update.
