### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by BronzeMantis** [OpenThrone/OpenThrone#48]
I went to the battle logs and saw this and now I get it when trying to load my homepage too. The homepage loaded up after a break and then I tried to revisit the battle logs and got the same error and the homepage displays the same error again.
![broke](https://github.com/OpenThrone/OpenThrone/assets/150398391/17746316-ee15-4ff4-885d-ffe017be7b17)

**Comment by uaktags** [comment]
This has been resolved.
