### ISSUE TITLE
Charisma Points not working - User Dimez

### ISSUE THREAD

**Issue by Dimez123** [OpenThrone/OpenThrone#64]
Hello, I was curious first off if having Charisma maxed out 100 points meant 100% discount on all items and thus a user could buy an infinite amount of upgrades? Secondly the actual issue, I just realized after slotting points in charisma that the discount does not work. Items reduced prices are on the upgrade screen but when comparing actual gold taken during a purchase, it consumes the full original unit cost regardless of Charisma. Can this be fixed?

If the 100% discount would be unintended, or the charisma discount fix will take a while, is it possible to get a level up points reset on my account until charisma is working properly?

Thank you
Dimez (In OT discord)

**Comment by uaktags** [comment]
Thanks Dimez, i'll take a look!

**Comment by uaktags** [comment]
Charisma was reset to 0. 
- [ ] Need to investigate why discount isn't being calcuated.
- [ ] Implement a max # of proficiency points per area. Not sure what DT made it, but i'll set it to only a max of 75 can go to any 1 category. Definitely an oversight.
