### ISSUE TITLE
Won battle showing as a loss

### ISSUE THREAD

**Issue by wjrichardson84** [OpenThrone/OpenThrone#67]
![Screenshot 2024-05-15 025125](https://github.com/OpenThrone/OpenThrone/assets/150527682/589509fc-61cc-4d41-a709-3a873375319d)
Quite clearly a win but showing as a loss.

**Comment by uaktags** [comment]
Thanks for the report, taking a look!

**Comment by wjrichardson84** [comment]
happened again with another player.  Foxconn this time.

**Comment by wjrichardson84** [comment]
I am thinking the game might be counting the whole army size instead of just the defenders.  I cannot beat anybody despite handily covering their defense.

**Comment by uaktags** [comment]
Fixed now as of the latest #121 Attack system

**Comment by uaktags** [comment]
https://openthrone.dev/api/attack/retest/771
