### ISSUE TITLE
Cannot untrain Soldiers

### ISSUE THREAD

**Issue by Dimez123** [OpenThrone/OpenThrone#68]
Invalid unit to untrain: [object Object]

When entering an amount of soldiers to untrain or untrain all, I get the above red error.

**Comment by uaktags** [comment]
Can't reproduce. If its still happening, can you open up "Inspect Element" and go to "Network", then when you click the Untrain, you should be able to get the full error message:

![image](https://github.com/OpenThrone/OpenThrone/assets/893684/abac7ab2-a684-4ddb-932e-37fd007aae77)

**Comment by uaktags** [comment]
Nah this was good. So instead of "Initiator" click on "Response". Preview will give you just a little preview of everyhting, but may not include all the raw data, but Response should.

**Comment by uaktags** [comment]
but no need, logged in as you and could reproduce the error on your account. Taking a look!

**Comment by uaktags** [comment]
Try again when you can

**Comment by Dimez123** [comment]
Problem solved, thank you.
