### ISSUE TITLE
Program Error

### ISSUE THREAD

**Issue by Sinfulsolitude** [OpenThrone/OpenThrone#70]
When i click attack i get a program error, not sure what its about but i tried 3 dofferent browsers so i dont think its something on my end
![E2C67B41-944A-4F20-B4B1-7489A8403BEE](https://github.com/OpenThrone/OpenThrone/assets/170324284/fb967387-3ba8-4237-9d32-24c160bdf3d2)

**Comment by uaktags** [comment]
This has been resolved and further investigation to root cause is continuing under #71
