### ISSUE TITLE
User has broken units format in db.

### ISSUE THREAD

**Issue by Dimez123** [OpenThrone/OpenThrone#71]
1 of 1 unhandled error
Server Error

TypeError: Cannot use 'in' operator to search for 'props' in undefined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:/home/tim/next-DC/node_modules/next-superjson-plugin/dist/tools.js (80:39)
step
file:/home/tim/next-DC/node_modules/next-superjson-plugin/dist/tools.js (45:23)
Object.next
file:/home/tim/next-DC/node_modules/next-superjson-plugin/dist/tools.js (26:53)
fulfilled
file:/home/tim/next-DC/node_modules/next-superjson-plugin/dist/tools.js (17:58)

**Comment by uaktags** [comment]
Got it, this should be resolved now, but the cause is still being investigated.

Findings: 
A user's units json became corrupt by turning it from a JSON into instead an object with a "units" key that held the correct Unit JSON.
