### ISSUE TITLE
Repair fort semi-broke

### ISSUE THREAD

**Issue by Dimez123** [OpenThrone/OpenThrone#78]
![repair broke](https://github.com/OpenThrone/OpenThrone/assets/132112018/b8510e73-30db-44a5-9ada-afbf54044b76)

[Issue] The repair button will keep consuming gold upon every click even if max repair is complete. 
[Quality of life] The old method I could just click repair, even with 0 inputted into the box and it would auto repair to max health. In this version I have to type in the amount I want repaired. In my opinion, this extra step, however simple, is a drop in the QoL of the repair tab. I end up staying on this page longer than I needed to compared to the past.

I don't know what changes were made, if any, to the repair screen, but I would say in short, I prefer it the old way.

**Comment by uaktags** [comment]
The errors are fixed, the percentage is now rounded down to the nearest integer correctly, and the repair will correctly fail to prevent going above max.

Some things I'll note on the UI, as its not fully obvious and this is an area i need help with from a design perspective:
- "Max: ##" can be clicked on to populate the input field to be that number. 
- The input has also been updated with a max and min so you can't go into the negative and the field will disable if you're fully repaired
- The change from the table based approach to the two cards makes it easier for resizability/responsiveness. Later this will also open the doors to better visual elements.

Two points I want to bring up for further discussion (in addition to any of the above points)
- Should the "Repair Max" be brought back in, in addition/leu of the "Max: ##" functionality?
- Is there anything that can be done to this new design to make it more appealing/intuitive?

**Comment by Dimez123** [comment]
Three things, one as a bug issue, two in response to your first question, and three in response to your second question:

One, I think there is still a repair problem with displayed max fort health. At level 15 the fort has 500hp. I was attacked at 1124 this morning, I repaired to 500 30 minutes later and submitted this initial bug report. I have come to look at the repair screen again and my fort health is back to 300/500, despite not being attacked. I repaired again just now; however my max allowable repair limit is 300, which doesn't permit my keep to reach its max health of 500. The two below images illustrate this.

Two, "Should the "Repair Max" be brought back in, in addition/leu of the "Max: ##" functionality?"

I think the (Reset) button and (Max ##) should be removed and the (Repair) button should always just function as a 1-click "repair all".
While a user does lose some fidelity by removing the (Max ##) function. In my opinion, it's not needed. The amount of gold someone makes compared to the cost it takes to repair fully is trivial... practically inconsequential. In example, a 500hp fort at 75gold per hp is 37,500 gold cost, or ~750 workers over one gold-gain cycle. Less workers over a few more cycles or with income level point allocation or worker economy upgrades. In short, a user is likely to never be in a position where they don't have the gold to repair their fort and need the (Max ##) function or (Reset) functions.

Three, Is there anything that can be done to this new design to make it more appealing/intuitive?
I think the Community and Social tabs can be merged. Also, when hovering over the Home-Battle-Structure-Social-Community-Sign out tabs, list the sub-tabs vertically like a drop-down bar instead of horizontally underneath. The sub-tabs appear by hovering the cursor over the main tab and all sections can be reached by clicking one time. Keep the black nighttime friendly background. No extra mouse actions required and the list would have the same font size. Not too large where it obnoxiously covers the screen, but not so small where it takes people extra time just to read what is being listed. Those are my suggestions for your two questions.

Thank you

![repair 1](https://github.com/OpenThrone/OpenThrone/assets/132112018/0e11dea1-b39f-46e7-b4ec-a8b005b945dd)
![repair 2](https://github.com/OpenThrone/OpenThrone/assets/132112018/24ff87b2-c69f-43d6-a3c3-498d15925070)

**Comment by uaktags** [comment]
Gotcha, so that actually points out a more systemic issue. The correct value for your Fort's MaxHP is indeed 300.
There's actually an embarrasing issue of how we were grabbing the current fort for the user, and it was grabbing the one higher.
I've added to the Structure Upgrades page for Forts to show their MaxHP.
Here's the current breakdown of forts https://github.com/OpenThrone/OpenThrone/blob/master/src/constants/Fortifications.tsx

**Comment by Dimez123** [comment]
Fair enough, thanks for clarifying
