### ISSUE TITLE
Unable to check war history

### ISSUE THREAD

**Issue by SofaKingJaded** [OpenThrone/OpenThrone#82]
`Unhandled Runtime Error

Error: Objects are not valid as a React child (found: object with keys {attacker, defender}). If you meant to render a collection of children, use an array instead.
Call Stack
throwOnInvalidObjectType
node_modules/react-dom/cjs/react-dom.development.js (14887:0)
createChild
node_modules/react-dom/cjs/react-dom.development.js (15139:0)
reconcileChildrenArray
node_modules/react-dom/cjs/react-dom.development.js (15404:0)
reconcileChildFibers
node_modules/react-dom/cjs/react-dom.development.js (15821:0)
reconcileChildren
node_modules/react-dom/cjs/react-dom.development.js (19167:0)
updateHostComponent
node_modules/react-dom/cjs/react-dom.development.js (19924:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (21618:0)
callCallback
node_modules/react-dom/cjs/react-dom.development.js (4164:0)
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (4213:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4277:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (27451:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (26557:0)
workLoopConcurrent
node_modules/react-dom/cjs/react-dom.development.js (26543:0)
renderRootConcurrent
node_modules/react-dom/cjs/react-dom.development.js (26505:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25738:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)`

`Unhandled Runtime Error

Error: Objects are not valid as a React child (found: object with keys {attacker, defender}). If you meant to render a collection of children, use an array instead.
Call Stack
throwOnInvalidObjectType
node_modules/react-dom/cjs/react-dom.development.js (14887:0)
createChild
node_modules/react-dom/cjs/react-dom.development.js (15139:0)
reconcileChildrenArray
node_modules/react-dom/cjs/react-dom.development.js (15404:0)
reconcileChildFibers
node_modules/react-dom/cjs/react-dom.development.js (15821:0)
reconcileChildren
node_modules/react-dom/cjs/react-dom.development.js (19167:0)
updateHostComponent
node_modules/react-dom/cjs/react-dom.development.js (19924:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (21618:0)
callCallback
node_modules/react-dom/cjs/react-dom.development.js (4164:0)
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (4213:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4277:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (27451:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (26557:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (26466:0)
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js (26434:0)
recoverFromConcurrentError
node_modules/react-dom/cjs/react-dom.development.js (25850:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25750:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)`

**Comment by uaktags** [comment]
Thanks, this is related to the ongoing Attack mechanism changes. Will get it fixed up with it though.
