### ISSUE TITLE
How should upgrading Forts affect Fort Health

### ISSUE THREAD

**Issue by Revenate39** [OpenThrone/OpenThrone#84]
I recently purchased the village upgrade and my fort health appears as 50/100. I would think that this upgrade would maintain fort health at 100%.

![Screenshot_20240603-085443](https://github.com/OpenThrone/OpenThrone/assets/171521017/8540b473-3041-477e-a730-f7753c641415)

**Comment by uaktags** [comment]
Good point, so upgrading the fort, would we expect that the fort level would be 100%, or would it be the difference between the new fort's max and the current forts HP?

For instance, your original fort had a max HP of 50 and the new fort has a max HP of 100. If your current fort is at say, 25hp health, and you upgrade to the next fort, would you expect to be fully healed at 100 or would you expect to be partially healed to 75 (+50 for the new HP, -25 for the damage you had)

**Comment by Revenate39** [comment]
I'm leaning towards that a fort upgrade fully heals your fort if it isn't 100%. I'm not sure what the gold gain advantage is for the later levels, but I'm currently looking at it costing 15 gold per point for repair (so to completely heal my 100 fort health costs 1500 gold).

Otherwise if the costings dramatically increase in the later levels then having a prompt that you have to fully repair your fort as a requirement before upgrading, and the fort upgrade maintains fort health at 100%.

**Comment by NunosDC** [comment]
I agree with Revenate and DT Gold gave you full fort if you bought the next upgrade. 

As far as if your current fort is in disrepair before the purchase perhaps a prompt that tells you to repair your current fort before buying the upgrade is the best seems similar to needing to fix something on your car to support adding that new turbo.

**Comment by uaktags** [comment]
All makes sense to me as well. 
I think for user experience i'll set it to 100% upon the upgrade. 
We can easily tie in a "pay for repairs" + upgrade workflow so its all 1 single click later, but I'd hate to get caught in the very specific and possibly unlikely situation where you have someone massing you as you're trying to upgrade your fort, causing you to go back and forth between repairs and upgrades.

For now though, when i push the fix, it'll cost whatever the upgrade costs and it'll take you from X value to 100% at no additional charge.
