### ISSUE TITLE
Auto Recruiter

### ISSUE THREAD

**Issue by NunosDC** [OpenThrone/OpenThrone#88]
When new accounts join the game the recruiter will not auto recruit them unless there are several accounts. It starts, clicks, then does the 3 second delay, but stops here.

Would be better for sakes of everyone being able to get the same number of recruits per 24 hours if these new accounts were set as ineligble for recruiting until the new day at 00:00 OTT, Open Throne Time.

**Comment by uaktags** [comment]
Both are fixed.
