### ISSUE TITLE
Training units bug

### ISSUE THREAD

**Issue by Revenate39** [OpenThrone/OpenThrone#97]
I currently cannot train more than single digit (1-9) of any unit, trying to enter a secondary number then becomes the default number. Essentially the last number pressed is what is trainable.
Numbers entered into the 'Convert' field work correctly.

**Comment by NunosDC** [comment]
I also am unable to train any unit types as it instantly reverts to 0 no matter what number I try. ;)

**Comment by uaktags** [comment]
Should be working now, thanks guys!
