### ISSUE TITLE
Armory Links

### ISSUE THREAD

**Issue by NunosDC** [OpenThrone/OpenThrone#98]
When trying to switch to other armory sections such as Spy, Defence, or Sentry the armory types do not change for me.

![image](https://github.com/OpenThrone/OpenThrone/assets/146961378/e4682779-61f7-4ef0-b41e-1be75ba1bb1b)

**Comment by uaktags** [comment]
Fix is ready to go up shortly. Also, i see in the screenshot that the bottom bar isn't acting correctly (it should be full width). Going to make a new ticket for the UI
